### ISSUE TITLE
Some Emojis are not displayed in the list

### ISSUE THREAD

**Issue by lemikeone** [mr-pennyworth/alfred-fastest-emoji#1]
Thanks for your great Workflow. 

I have notice that a fair amount of Emojis are not displayed in the Alfred Windows, but then, if I paste it in an app, it works well : 

![2020-11-26_10-26-49](https://user-images.githubusercontent.com/11621377/100339730-27a9a900-2fd2-11eb-94ee-20d86915a864.jpg)

![2020-11-26_10-27-48](https://user-images.githubusercontent.com/11621377/100339735-28dad600-2fd2-11eb-90b6-5c775d8e36f0.jpg)

Do you have any idea why? 

Thanks!

**Comment by mr-pennyworth** [comment]
@lemikeone thanks for reporting! :)

Lemme investigate this.
I think that icon isn't supported on Catalina, and as I generated the icons on Catalina, Apple's font could not create that icon.

In the meanwhile, if you don't minding using the joypixels version for some time, download that. All the icons are properly generated in that...

Also, could you share `/System/Library/Fonts/Apple Color Emoji.ttc` with me?
I don't plan to upgrade to BigSur anytime soon, but I could generate the apple icons using that font and update the workflow.

**Comment by lemikeone** [comment]
Sure, can you give me an email, as the limit on Github is 10MB, and this file is 200MB ;)

**Comment by mr-pennyworth** [comment]
@lemikeone sorry I somehow missed your reply!

Fixed in the latest release.

Instead of building the icons on my machine, I just moved the build process to github servers running BigSur.

**Comment by lemikeone** [comment]
> @lemikeone sorry I somehow missed your reply!
> 
> Fixed in the latest release.
> 
> Instead of building the icons on my machine, I just moved the build process to github servers running BigSur.

Great, thanks a lot 🚀

**Comment by lemikeone** [comment]
Works great now! : 

![2020-11-29_09-48-37](https://user-images.githubusercontent.com/11621377/100538519-2ffb2180-3228-11eb-8a35-2f3daf74db77.jpg)
