### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by krzkaczor** [mr-pennyworth/alfred-fastest-emoji#2]
How do I use this beautiful thing? 😆

**Comment by mr-pennyworth** [comment]
@krzkaczor you'll need [Alfred Power Pack](https://www.alfredapp.com/shop/).
After that, head over to [Downloads](https://github.com/mr-pennyworth/alfred-fastest-emoji/#downloads) and download for your desired language and emoji flavor.

Alfred should open and install the downloaded file when you double-click on it.

PS: Thanks! I've updated the readme.
