### ISSUE TITLE
Updating with newly released Emoji

### ISSUE THREAD

**Issue by pugson** [mr-pennyworth/alfred-fastest-emoji#4]
Fantastic workflow, thanks for building it!

How can I pull the latest emoji list and update the workflow to include them?

**Comment by mr-pennyworth** [comment]
Thanks @pugson! And apologies for the delayed response!
I have updated the repository with the latest builds.

To answer the question on how a person can do it on their own, here are the steps:
 - We get the emoji names and tags from [emojibase](https://github.com/milesj/emojibase).
    To update them, `cd emojibase && git pull && cd ..`.
 - We get the joypixels icons from [joypixels/emoji-assets](https://github.com/joypixels/emoji-assets).
    To update those, `cd joypixels && git pull && cd ..`.
 - Now that we have the latest icons and metadata, we can re-build the workflow
    by running `python3 build-scripts/mkworkflows.py`. At this point, the directory will contain
    all the newly built `.alfredworkflow` files, any of which can be installed with a double-click.

See [build.yml](https://github.com/mr-pennyworth/alfred-fastest-emoji/blob/main/.github/workflows/build.yml) for how the workflow is built in an automated manner on GitHub.
