### ISSUE TITLE
How to view in grid view?

### ISSUE THREAD

**Issue by yarub123** [mr-pennyworth/alfred-fastest-emoji#5]
I can only access the default Alfred list view.

Thanks in advance!

**Comment by mr-pennyworth** [comment]
You'll have to assign a trigger to the grid view:
<img width="576" alt="image" src="https://github.com/user-attachments/assets/cc790842-e3d4-4cf8-91cd-3f0946f19cd6">

Also, maybe you have an older version? 🤔
https://github.com/mr-pennyworth/alfred-fastest-emoji/releases

**Comment by yarub123** [comment]
oh yeah, duhhh. Thanks 🙃
